{
	"id": "oval:org.almalinux.alsa:def:20243275",
	"version": "636",
	"class": "patch",
	"metadata": {
		"Title": "ALSA-2024:3275: python-dns security update (Moderate)",
		"reference": [
			{
				"ref_id": "ALSA-2024:3275",
				"source": "ALSA",
				"ref_url": "https://errata.almalinux.org/8/ALSA-2024-3275.html"
			},
			{
				"ref_id": "CVE-2023-29483",
				"source": "CVE",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2023-29483"
			},
			{
				"ref_id": "ALSA-2024:3275",
				"source": "ALSA",
				"ref_url": "https://errata.almalinux.org/8/ALSA-2024-3275.html"
			}
		],
		"Description": "The python-dns package contains the dnslib module that implements a DNS client and additional modules that define certain symbolic constants used by DNS, such as dnstype, dnsclass and dnsopcode.\n\nSecurity Fix(es):\n\n* dnspython: denial of service in stub resolver (CVE-2023-29483)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
		"advisory": {
			"from": "packager@almalinux.org",
			"Severity": "Moderate",
			"Rights": "Copyright 2024 AlmaLinux OS",
			"issued": {
				"date": "2024-05-22"
			},
			"updated": {
				"date": "2024-05-22"
			},
			"affected_cpe_list": {
				"Cpe": [
					"cpe:/a:almalinux:almalinux:8",
					"cpe:/a:almalinux:almalinux:8::appstream",
					"cpe:/a:almalinux:almalinux:8::powertools",
					"cpe:/a:almalinux:almalinux:8::highavailability",
					"cpe:/a:almalinux:almalinux:8::nfv",
					"cpe:/a:almalinux:almalinux:8::realtime",
					"cpe:/a:almalinux:almalinux:8::resilientstorage",
					"cpe:/a:almalinux:almalinux:8::sap",
					"cpe:/a:almalinux:almalinux:8::sap_hana",
					"cpe:/a:almalinux:almalinux:8::supplementary",
					"cpe:/o:almalinux:almalinux:8",
					"cpe:/o:almalinux:almalinux:8::baseos"
				]
			},
			"bugzilla": [
				{
					"href": "https://bugzilla.redhat.com/2274520",
					"id": "2274520"
				}
			],
			"cve": [
				{
					"text": "CVE-2023-29483",
					"public": "20240209",
					"href": "https://access.redhat.com/security/cve/CVE-2023-29483",
					"impact": "Moderate",
					"cwe": "CWE-696",
					"cvss3": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterions": [
							{
								"test_ref": "oval:org.almalinux.alsa:tst:2020034810042",
								"comment": "python3-dns is signed with AlmaLinux OS 8 key (51d6647ec21ad6ea)"
							},
							{
								"test_ref": "oval:org.almalinux.alsa:tst:2020034810043",
								"comment": "python3-dns is signed with AlmaLinux OS 8 key (2ae81e8aced7258b)"
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:org.almalinux.alsa:tst:20243275001",
						"comment": "python3-dns is earlier than 0:1.15.0-12.el8_10"
					},
					{
						"test_ref": "oval:org.almalinux.alba:tst:20191992003",
						"comment": "AlmaLinux 8 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.almalinux.alba:tst:20191992005",
				"comment": "AlmaLinux must be installed"
			}
		]
	}
}
