{
	"id": "oval:org.almalinux.alsa:def:20245534",
	"version": "636",
	"class": "patch",
	"metadata": {
		"Title": "ALSA-2024:5534: python-setuptools security update (Important)",
		"reference": [
			{
				"ref_id": "ALSA-2024:5534",
				"source": "ALSA",
				"ref_url": "https://errata.almalinux.org/9/ALSA-2024-5534.html"
			},
			{
				"ref_id": "CVE-2024-6345",
				"source": "CVE",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2024-6345"
			},
			{
				"ref_id": "ALSA-2024:5534",
				"source": "ALSA",
				"ref_url": "https://errata.almalinux.org/9/ALSA-2024-5534.html"
			}
		],
		"Description": "The python-setuptools package provides a collection of enhancements to Python distribution utilities allowing convenient building and distribution of Python packages.\n\nSecurity Fix(es):\n\n* pypa/setuptools: Remote code execution via download functions in the package_index module in pypa/setuptools (CVE-2024-6345)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
		"advisory": {
			"from": "packager@almalinux.org",
			"Severity": "Important",
			"Rights": "Copyright 2024 AlmaLinux OS",
			"issued": {
				"date": "2024-08-19"
			},
			"updated": {
				"date": "2024-08-19"
			},
			"affected_cpe_list": {
				"Cpe": [
					"cpe:/a:almalinux:almalinux:9",
					"cpe:/a:almalinux:almalinux:9::appstream",
					"cpe:/a:almalinux:almalinux:9::crb",
					"cpe:/a:almalinux:almalinux:9::highavailability",
					"cpe:/a:almalinux:almalinux:9::nfv",
					"cpe:/a:almalinux:almalinux:9::realtime",
					"cpe:/a:almalinux:almalinux:9::resilientstorage",
					"cpe:/a:almalinux:almalinux:9::sap",
					"cpe:/a:almalinux:almalinux:9::sap_hana",
					"cpe:/a:almalinux:almalinux:9::supplementary",
					"cpe:/o:almalinux:almalinux:9",
					"cpe:/o:almalinux:almalinux:9::baseos"
				]
			},
			"bugzilla": [
				{
					"href": "https://bugzilla.redhat.com/2297771",
					"id": "2297771"
				}
			],
			"cve": [
				{
					"text": "CVE-2024-6345",
					"public": "20240715",
					"href": "https://access.redhat.com/security/cve/CVE-2024-6345",
					"impact": "Important",
					"cwe": "CWE-94",
					"cvss3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
				}
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:org.almalinux.alsa:tst:20245534001",
										"comment": "python3-setuptools is earlier than 0:53.0.0-12.el9_4.1"
									},
									{
										"test_ref": "oval:org.almalinux.alsa:tst:20230952002",
										"comment": "python3-setuptools is signed with AlmaLinux OS 9 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:org.almalinux.alsa:tst:20245534003",
										"comment": "python3-setuptools-wheel is earlier than 0:53.0.0-12.el9_4.1"
									},
									{
										"test_ref": "oval:org.almalinux.alsa:tst:20230952004",
										"comment": "python3-setuptools-wheel is signed with AlmaLinux OS 9 key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:org.almalinux.alba:tst:20223893007",
						"comment": "AlmaLinux 9 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.almalinux.alba:tst:20223893008",
				"comment": "AlmaLinux must be installed"
			}
		]
	}
}
