{
	"id": "oval:org.almalinux.alsa:def:20249423",
	"version": "635",
	"class": "patch",
	"metadata": {
		"Title": "ALSA-2024:9423: python-dns security update (Moderate)",
		"reference": [
			{
				"ref_id": "CVE-2023-29483",
				"source": "CVE",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2023-29483"
			},
			{
				"ref_id": "RHSA-2024:9423",
				"source": "RHSA",
				"ref_url": "https://access.redhat.com/errata/RHSA-2024:9423"
			},
			{
				"ref_id": "ALSA-2024:9423",
				"source": "ALSA",
				"ref_url": "https://errata.almalinux.org/9/ALSA-2024-9423.html"
			}
		],
		"Description": "The python-dns package contains the dnslib module that implements a DNS client and additional modules that define certain symbolic constants used by DNS, such as dnstype, dnsclass and dnsopcode.  \n\nSecurity Fix(es):  \n\n  * dnspython: denial of service in stub resolver (CVE-2023-29483)\n\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.  \n\nAdditional Changes:  \n\nFor detailed information on changes in this release, see the AlmaLinux Release Notes linked from the References section.\n",
		"advisory": {
			"from": "packager@almalinux.org",
			"Severity": "Moderate",
			"Rights": "Copyright 2024 AlmaLinux OS",
			"issued": {
				"date": "2024-11-12"
			},
			"updated": {
				"date": "2024-11-12"
			},
			"affected_cpe_list": {
				"Cpe": [
					"cpe:/a:almalinux:almalinux:9",
					"cpe:/a:almalinux:almalinux:9::appstream",
					"cpe:/a:almalinux:almalinux:9::crb",
					"cpe:/a:almalinux:almalinux:9::highavailability",
					"cpe:/a:almalinux:almalinux:9::nfv",
					"cpe:/a:almalinux:almalinux:9::realtime",
					"cpe:/a:almalinux:almalinux:9::resilientstorage",
					"cpe:/a:almalinux:almalinux:9::sap",
					"cpe:/a:almalinux:almalinux:9::sap_hana",
					"cpe:/a:almalinux:almalinux:9::supplementary",
					"cpe:/o:almalinux:almalinux:9",
					"cpe:/o:almalinux:almalinux:9::baseos"
				]
			},
			"bugzilla": [
				{
					"href": "https://bugzilla.redhat.com/2274520",
					"id": "2274520"
				}
			],
			"cve": [
				{
					"text": "CVE-2023-29483",
					"public": "20240209",
					"href": "https://access.redhat.com/security/cve/CVE-2023-29483",
					"impact": "Moderate",
					"cwe": "CWE-696",
					"cvss3": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:org.almalinux.alba:tst:20225749023",
						"comment": "AlmaLinux 9 is installed"
					},
					{
						"test_ref": "oval:org.almalinux.alsa:tst:20249423001",
						"comment": "python3-dns is earlier than 0:2.6.1-3.el9"
					},
					{
						"test_ref": "oval:org.almalinux.alsa:tst:20249423002",
						"comment": "python3-dns is signed with AlmaLinux OS 9 key (d36cb86cb86b3716)"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.almalinux.alba:tst:20225749024",
				"comment": "AlmaLinux must be installed"
			}
		]
	}
}
